# Generated by Django 3.2.14 on 2022-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('name', models.TextField()),
                ('reg', models.IntegerField(primary_key=True, serialize=False)),
                ('mydate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
