# Generated by Django 3.2.14 on 2022-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mydate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
