# Generated by Django 3.2.14 on 2022-08-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0002_auto_20220810_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dip',
            new_name='Dupe',
        ),
    ]
