# Generated by Django 3.2.14 on 2022-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0004_rename_dupe_dupee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupee',
            name='mymonth',
            field=models.DateField(auto_now=True),
        ),
    ]
