# Generated by Django 3.2.14 on 2022-08-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0005_dupee_mymonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupee',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
