# Generated by Django 3.2.15 on 2022-08-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boapp', '0006_dupee_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupee',
            name='grade',
        ),
    ]
